### ISSUE TITLE
Windows Compile/Release

### ISSUE THREAD

**Issue by jerry-synap** [Pulimet/ADBugger#29]
Hello,

Is it possible to compile this code into an (exe)? I see you have (dmg) in your releases section and I want to test this desktop application of yours. Thanks

**Comment by Pulimet** [comment]
Hi,

The next release will include a Windows version (v.1.0.3). I'll post an update here when it's ready.

**Comment by Pulimet** [comment]
Hi, please check the latest, 1.0.3 release:

https://github.com/Pulimet/ADBugger/releases/tag/v1.0.3

Unfortunately, I don't have any Windows laptops around to check it.

**Comment by Pulimet** [comment]
You are welcome!

If you have any issues/crashes/feature requests please feel free to open new Github issues. 

Also please note the roadmap:

https://github.com/users/Pulimet/projects/1/views/1

Best wishes,
Alexey
