### ISSUE TITLE
Devices Don't Appear

### ISSUE THREAD

**Issue by DroidlyMobile** [Pulimet/ADBugger#31]
I can connect my devices via Platform Tools but this tool isn't seeing my devices

**Comment by Pulimet** [comment]
First of all excuse me for the delay. 

1.  Which platform do you use? (Mac/Win)
2. What is the path to your platform tools?
3. If it isn't the same as on snapshot, please update the path:
4. 
<img width="612" alt="image" src="https://github.com/user-attachments/assets/c0995611-7d8b-47d3-8213-d40ca240d720">

**Comment by Pulimet** [comment]
@DroidlyMobile, feel free to reopen/comment here when you get the answers.

**Comment by Pulimet** [comment]
Just created alpha1 of the future 1.0.5 version with a path checker.
<img width="832" alt="image" src="https://github.com/user-attachments/assets/80ce579d-2f04-49cc-97ab-90412eea7768">

If the path is ok after clicking on the buttons they will become green:
<img width="642" alt="image" src="https://github.com/user-attachments/assets/f4261e0f-f48a-406b-b3aa-26668655d63e">

In ADB Logs section you should see:
<img width="431" alt="image" src="https://github.com/user-attachments/assets/ecccc9d1-455d-4547-88f2-c5056373c951">

<img width="431" alt="image" src="https://github.com/user-attachments/assets/1f01d518-604a-4283-978d-0a7870e2093d">
